name: Publish to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        uses: shalzz/zola-deploy-action@v0.19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
